"""empty message

Revision ID: 54a3a08a8260
Revises: d3098b458230
Create Date: 2021-02-15 19:57:05.356805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a3a08a8260'
down_revision = 'd3098b458230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('allow_news_letter', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'subscription', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='unique')
    op.drop_column('subscription', 'allow_news_letter')
    # ### end Alembic commands ###
